### PR TITLE
Created more tests

### PR DESCRIPTION
**Pull request by LuisAbularach**
Created more tests this time for Timberutil dealing with retrieving the correct colors and IP address, still need to get better with knowing how a lot of the methods work and using Junit with android. (SearchActivityTest.java was one of last week's commit)

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @areeba-waheed

**Comment by kyledewey** [comment]
Additionally assigned @dou10

**Review by dou10 — APPROVED** [review]
Clear and easy to read

**Review by areeba-waheed — APPROVED** [review]
Testing search activity looks good. Clean code and easy to read. Good Job!

**Pull request merged**
